#!/bin/bash

# load basic app files
. ./app/user_func.sh
. ./app/config.sh
. ./app/text.sh

# User Info Gathering
clear

u_set_default_removes

#echo $not_install
return 0

IFS=', ' read -r -a remove <<< "$not_install"

if [[ " ${remove[*]} " =~ "Q" ]]; then
	    # whatever you want to do when array contains value
fi
