#!/bin/bash

# Script Config
default_apps=("tmux (screen multiplxer) - provides ability to split screen" 
	      "Vim (text editor)" 
	      "Lynx (web browser) - will also install PowerTools repo")

# User Info Gathering
clear

echo "
#################################
# Terminal Workstation Install #
#################################

Hello, thank you for choosing our Terminal Workstation, for your basic terminal 
needs.

No changes will be made to your system during this phase. Feel free to exit 
the installion at any point. 

By default the following tools, and their required packages, will be installed:"

for i in ${!default_apps[@]}; do
	echo "$(($i+1)). ${default_apps[$i]}"
done

echo "Q. Quit

If you do NOT want to install any of these tools, please list them by number
seperated by a comma:"
read not_install

echo $not_install
