#!/bin/bash

##############################
#
# Project: Terminal Workstation
# Author: Al Fama (afama8 - GitHub)
# License: GNU General Public License v3.0
# Repository: git@github.com:afama8/terminal-workstation.git
#
# File: station_install.sh
# Purpose: Initial script to pass process to controller.
# Visibility: Global
# Global Variables (created, updated): None
#
# File Loads:
# - config.sh: Application configuration file
# - controller/main.sh: Provide access to all application workflows
#
##############################
. ./config.sh
. ./controller/main.sh


# Start app
clear
fwcm_main


echo "So far, so good"


